version: "3.8"
services:
  predictor:
    container_name: "predictor"
    image: "martinabeleda/ai-auto-challenge:latest"
    build: ./
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    volumes:
        - .:/app
    ports:
      - 8080:80
